version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: devsecops-tp04-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: usersdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: ChangeMe123!
    volumes:
      - ./database/seed.sql:/docker-entrypoint-initdb.d/seed.sql
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: devsecops-tp04-backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: usersdb
      DB_USER: admin
      DB_PASSWORD: ChangeMe123!
    networks:
      - app_network
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  frontend:
    image: nginx:latest
    container_name: devsecops-tp04-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:


networks:
  app_network:
    name: devsecops-tp04-network
